create cronjob task
Paulo-Abreu/libraryOn pull request #4
Opened 2022-05-23 18:16 UTC by Paulo-Abreu

Here I created the cronjob task for the loans

![image](https://user-images.githubusercontent.com/56804712/169881893-da59c841-ae02-4bbb-8fdd-058662f47776.png)

2022-05-23 18:24 UTC, jeanfelipe-spec requested changes
Gostei de ter aprendido sobre cronjob, seu primeiro contato, mandou bem.
Deixei alguns comentarios de alteracoes, e roda o rubocop tbm plz.
Adiciona a gem `rubocop` e instala no seu vscode a extensao, ai fica rodando toda hora ja.

2022-05-23 18:24 UTC, jeanfelipe-spec commented on lib/tasks/batch.rake
> +    @loans = BookLoan.all
Esse cronjob, precisa verificar os livros atrasados, aqui esta apenas pegando todos os emprestimos, precisa filtrar pela data de hoje e pelo status `nao entregue`(em ingles)

2022-05-23 18:24 UTC, jeanfelipe-spec commented on config/schedule.rb
> +every 24.hours do
especifique que ele vai rodar todos os dias as 2 da manha, plz

2022-05-23 18:24 UTC, jeanfelipe-spec commented on app/controllers/books_controller.rb
> +  before_action :load_book, only: [:update, :destroy, :loan]
quando comeca a ter muitas actions dentro do bloco `only` e melhor mudar ele para `except` e colocar no array apenas os metodos que nao devem ser executados caso seja menos, aqui no caso vai ser menos por que vai ser o destroy

2022-05-23 18:24 UTC, jeanfelipe-spec commented on Gemfile
> +
linha extra aqui

2022-05-30 17:41 UTC, jean-felipe commented on app/controllers/books_loans_controller.rb
> +
linha extra aqui, pode remover e adicinoar uma antes do `if`

2022-05-30 17:43 UTC, jean-felipe commented on lib/tasks/batch.rake
> +    @loans = BookLoan.find_by loan_type:0
Quando voce usa `enums` o rails cria automagicamente `scopes` de acordo com o enum, aqui nessa linha voce pode trocar por:
`BookLoan.not_returned`

2022-05-31 17:47 UTC, merged